import os

class IntelligenceFusionEngine:
    def __init__(self):
        pass

    def get_user_genetic_vulnerability(self, user_id: str) -> dict:
        """
        Mock function to fetch user's genetic vulnerability.
        In production, this would query Supabase for the user's parsed genome reports
        (generated by disease_risk_analyzer.py) to check for inflammatory/immune SNPs.
        """
        # For MVP, we simulate a few user profiles based on ID
        if user_id == "user_high_risk":
            return {
                "inflammatory_risk": "HIGH",
                "immune_compromised": True,
                "relevant_snps": ["IL6_rs1800795_G", "TNF_rs1800629_A"],
                "base_multiplier": 1.5
            }
        elif user_id == "user_medium_risk":
            return {
                "inflammatory_risk": "MEDIUM",
                "immune_compromised": False,
                "relevant_snps": ["IL6_rs1800795_G"],
                "base_multiplier": 1.2
            }
        else:
            return {
                "inflammatory_risk": "LOW",
                "immune_compromised": False,
                "relevant_snps": [],
                "base_multiplier": 1.0
            }

    def generate_personalized_insights(self, outbreak_risk_data: dict, genetic_vulnerability: dict) -> dict:
        """
        Fuses environmental outbreak risk with genetic vulnerability to generate personalized protocols.
        """
        base_risk_score = outbreak_risk_data.get('risk_score', 0)
        multiplier = genetic_vulnerability.get('base_multiplier', 1.0)
        
        # Calculate personalized severity risk
        personalized_score = min(base_risk_score * multiplier, 100)
        
        # Determine threat level
        if personalized_score > 80:
            threat_level = "CRITICAL"
        elif personalized_score > 50:
            threat_level = "ELEVATED"
        else:
            threat_level = "STANDARD"
            
        # Generate personalized protocols
        protocols = []
        if threat_level == "CRITICAL" and genetic_vulnerability.get('inflammatory_risk') == "HIGH":
            protocols.append("Your genetic profile shows high inflammatory reactivity. Begin preemptive anti-inflammatory protocols (Curcumin, EPA/DHA) immediately.")
            protocols.append("Strict mosquito avoidance required. Use DEET-based repellents and ensure window screens are intact.")
        elif threat_level == "ELEVATED":
            protocols.append("Dengue risk is rising in your area. Maintain standard precautions and boost Vitamin C and Zinc intake.")
            if genetic_vulnerability.get('inflammatory_risk') in ["MEDIUM", "HIGH"]:
                protocols.append("Monitor for early symptoms of inflammation like joint pain.")
        else:
            protocols.append("Environmental risk is currently low. Maintain baseline health protocols.")
            
        return {
            "personalized_score": float(personalized_score),
            "threat_level": threat_level,
            "genetic_factors_considered": genetic_vulnerability.get('relevant_snps', []),
            "recommended_protocols": protocols,
            "outbreak_context": outbreak_risk_data.get('insights', [])
        }

if __name__ == "__main__":
    engine = IntelligenceFusionEngine()
    
    # Mock outbreak data from outbreak_model.py
    mock_outbreak = {
        "risk_score": 60.0,
        "insights": ["Heavy rainfall over the last 14 days has created optimal breeding grounds."]
    }
    
    print("Testing High Risk User:")
    vuln = engine.get_user_genetic_vulnerability("user_high_risk")
    result = engine.generate_personalized_insights(mock_outbreak, vuln)
    print(result)
    
    print("\nTesting Normal User:")
    vuln = engine.get_user_genetic_vulnerability("user_normal")
    result = engine.generate_personalized_insights(mock_outbreak, vuln)
    print(result)
